# Generated by Django 5.2.7 on 2025-10-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пополнения')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='accounting.client')),
            ],
            options={
                'verbose_name': 'Пополнение клиента',
                'verbose_name_plural': 'Пополнения клиентов',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма выплаты')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounting.worker')),
            ],
            options={
                'verbose_name': 'Выплата сотруднику',
                'verbose_name_plural': 'Выплаты сотрудникам',
                'ordering': ['-date_time'],
            },
        ),
    ]
