# Generated by Django 5.2.7 on 2025-10-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_clientdeposit_workerpayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_time'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receipt_printed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Пополнение'), ('OUT', 'Оплата приема')], default='IN', max_length=3, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='worker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сотрудник, проводивший прием'),
        ),
    ]
