# Generated by Django 5.2.7 on 2025-10-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='balance',
        ),
        migrations.DeleteModel(
            name='WorkerPayout',
        ),
    ]
