# Generated by Django 6.0.1 on 2026-02-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_add_receipt_balance_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(max_length=200, verbose_name="ФИО"),
        ),
    ]
